#page title
page_title                                : Codator - code-server

# App Info
ios_app_id                                :                                           1504491325

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : appicon.png
app_name                                  : Codator
app_price                                 : 2.99$ /month (Free with self hosted server)
app_description                           : Online code editor

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Adrian Labbé

your_link                                 : https://labbe.me

your_city                                 : Viña Del Mar
email_address                             : adrian@labbe.me
facebook_username                         :                                           
instagram_username                        :
twitter_username                          : develobile
github_username                           : ColdGrub1384
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.

features                                  :
    
  - title                                 : Online
    description                           : This app is not an official version of Visual Studio Code. It uses <a href="https://github.com/cdr/code-server">code-server</a>, a browser version of VS Code already hosted so there is nothing to setup unless you want to use your own server.
    fontawesome_icon_name                 : globe

  - title                                 : Edit local files
    description                           : Upload local files and edit them with the code editor.
    fontawesome_icon_name                 : keyboard

  - title                                 : Preview HTML
    description                           : Preview your HTML pages on the app while editing.
    fontawesome_icon_name                 : eye

  - title                                 : Your own editor
    description                           : Personalize the editor by installing extensions or run any Linux command with the terminal.
    fontawesome_icon_name                 : terminal

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000000"

cover_image                               :                  # Replace with alternative image path or image URL.
cover_overlay_color                       : "#ffffff"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ededed"

link_color                                : "#1d63ea"

app_title_color                           : "#000000"
app_price_color                           : "#000000"
app_description_color                     : "#000000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

theme: jekyll-theme-cayman
